[package]
name = "circular-buffer-zero-size-start"
version = "0.1.0"
authors = ["philip.a.markgraf <philip_markgraf@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
